# Generated by Django 5.2.7 on 2025-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakaslistportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
