# Generated by Django 5.2.7 on 2025-10-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sakaslistportal", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="query_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
