# Generated by Django 5.2.7 on 2025-10-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sakaslistportal", "0004_query_query_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="query_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
